# Generated by Django 3.2.11 on 2022-01-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='listings.photoalbum'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='apt_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
    ]
