# Generated by Django 3.2.11 on 2022-01-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20220121_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
