# Generated by Django 3.2.11 on 2022-01-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_photo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
