# Generated by Django 3.2.11 on 2022-01-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_photo_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.photoalbum'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='photo',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
