# Generated by Django 3.2.11 on 2022-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='name',
        ),
        migrations.AddField(
            model_name='realtor',
            name='f_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='l_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
