# Generated by Django 3.2.11 on 2022-02-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inquiry',
        ),
    ]
